//
// Created by jayan on 24-08-2025.
//

#ifndef SMALLEST_AND_LARGEST_ELEMENT_OF_ARRAY_H
#define SMALLEST_AND_LARGEST_ELEMENT_OF_ARRAY_H



class SMALLEST_AND_LARGEST_ELEMENT_OF_ARRAY {

};



#endif //SMALLEST_AND_LARGEST_ELEMENT_OF_ARRAY_H
