//
// Created by jayan on 24-08-2025.
//

#ifndef SUM_AND_PRODUCT_OF_ALL_NUMBERS_IN_AN_ARRAY_H
#define SUM_AND_PRODUCT_OF_ALL_NUMBERS_IN_AN_ARRAY_H



class SUM_AND_PRODUCT_OF_ALL_NUMBERS_IN_AN_ARRAY {

};



#endif //SUM_AND_PRODUCT_OF_ALL_NUMBERS_IN_AN_ARRAY_H
